# -*- coding: utf-8 -*-
"""DL_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llt3BY_XLVePqFFjFP9GNQvKEgtyJiMN

# **AND Fixed values**
"""

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

w = np.zeros(2)
b = 0
lr = 0.1

for _ in range(100):
    for i in range(len(X)):
        y_pred = 1 if np.dot(X[i],w)+b >= 0 else 0
        error = y[i] - y_pred
        w += lr * error * X[i]
        b += lr * error

pred = [1 if np.dot(x,w)+b>=0 else 0 for x in X]
acc = np.mean(pred == y) * 100

print("Weights:", w)
print("Bias:", b)
print("Error:", np.sum((y - pred)**2))
print("Accuracy:", acc, "%")

"""# **AND – Random Values**"""

import numpy as np

X = np.random.randint(0,2,(1000,2))
y = np.logical_and(X[:,0],X[:,1]).astype(int)

w = np.zeros(2)
b = 0
lr = 0.1

for _ in range(100):
    for i in range(len(X)):
        y_pred = 1 if np.dot(X[i],w)+b >= 0 else 0
        error = y[i] - y_pred
        w += lr * error * X[i]
        b += lr * error

pred = (np.dot(X,w)+b>=0).astype(int)
acc = np.mean(pred == y) * 100

print("Weights:", w)
print("Bias:", b)
print("Error:", np.mean((y - pred)**2))
print("Accuracy:", acc, "%")

"""# **OR – Fixed Values**"""

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])

w = np.zeros(2)
b = 0
lr = 0.1

for _ in range(100):
    for i in range(len(X)):
        y_pred = 1 if np.dot(X[i],w)+b >= 0 else 0
        error = y[i] - y_pred
        w += lr * error * X[i]
        b += lr * error

pred = [1 if np.dot(x,w)+b>=0 else 0 for x in X]
acc = np.mean(pred == y) * 100

print("Weights:", w)
print("Bias:", b)
print("Error:", np.sum((y - pred)**2))
print("Accuracy:", acc, "%")

"""# **OR – Random Values**"""

import numpy as np

X = np.random.randint(0,2,(1000,2))
y = np.logical_or(X[:,0],X[:,1]).astype(int)

w = np.zeros(2)
b = 0
lr = 0.1

for _ in range(100):
    for i in range(len(X)):
        y_pred = 1 if np.dot(X[i],w)+b >= 0 else 0
        error = y[i] - y_pred
        w += lr * error * X[i]
        b += lr * error

pred = (np.dot(X,w)+b>=0).astype(int)
acc = np.mean(pred == y) * 100

print("Weights:", w)
print("Bias:", b)
print("Error:", np.mean((y - pred)**2))
print("Accuracy:", acc, "%")

"""# **XOR – Fixed Values**"""

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

np.random.seed(0)
w1 = np.random.rand(2,4)
b1 = np.random.rand(1,4)
w2 = np.random.rand(4,1)
b2 = np.random.rand(1,1)

lr = 0.1

def sigmoid(x): return 1/(1+np.exp(-x))

for _ in range(5000):
    h = sigmoid(X@w1 + b1)
    out = sigmoid(h@w2 + b2)
    error = y - out
    w2 += lr * h.T @ error
    b2 += lr * np.sum(error)
    w1 += lr * X.T @ (error@w2.T)
    b1 += lr * np.sum(error)

pred = (out>0.5).astype(int)
acc = np.mean(pred==y)*100

print("Weights 1:", w1)
print("Bias 1:", b1)
print("Weights 2:", w2)
print("Bias 2:", b2)
print("Error:", np.mean(error**2))
print("Accuracy:", acc, "%")

"""# **XOR – Random Values**"""

import numpy as np

# Stable sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -50, 50)))

def d_sigmoid(x):
    s = sigmoid(x)
    return s * (1 - s)

# Data
X = np.random.randint(0, 2, (1000, 2))
y = np.logical_xor(X[:,0], X[:,1]).astype(int).reshape(-1,1)

# Initialize weights
np.random.seed(1)
w1 = np.random.randn(2, 8)
b1 = np.zeros((1,8))
w2 = np.random.randn(8, 1)
b2 = np.zeros((1,1))

lr = 0.05

# Training
for _ in range(3000):
    z1 = X @ w1 + b1
    a1 = sigmoid(z1)
    z2 = a1 @ w2 + b2
    out = sigmoid(z2)

    error = y - out

    d2 = error * d_sigmoid(z2)
    d1 = d2 @ w2.T * d_sigmoid(z1)

    w2 += lr * a1.T @ d2
    b2 += lr * np.sum(d2, axis=0)
    w1 += lr * X.T @ d1
    b1 += lr * np.sum(d1, axis=0)

# Results
pred = (out > 0.5).astype(int)
acc = np.mean(pred == y) * 100
mse = np.mean(error**2)

print("Hidden Weights:", w1)
print("Hidden Bias:", b1)
print("Output Weights:", w2)
print("Output Bias:", b2)
print("Final Error:", mse)
print("Accuracy:", acc, "%")



"""# **Stochastic Gradient Descent**"""

import numpy as np

X = np.array([1,2,3,4])
y = np.array([2,4,6,8])
w = 0.0
lr = 0.01

for _ in range(1000):
    i = np.random.randint(len(y))
    grad = (w*X[i] - y[i]) * X[i]
    w -= lr * grad

pred = w * X
error = np.mean((y - pred)**2)
acc = (1 - error / np.var(y)) * 100

print("Stochastic GD")
print("Weight:", w)
print("Error:", error)
print("Accuracy:", acc, "%")

"""# **Mini-Batch Gradient Descent**"""

import numpy as np

X = np.array([1,2,3,4])
y = np.array([2,4,6,8])
w = 0.0
lr = 0.01
batch_size = 2

for _ in range(1000):
    idx = np.random.choice(len(y), batch_size)
    grad = np.mean((w*X[idx] - y[idx]) * X[idx])
    w -= lr * grad

pred = w * X
error = np.mean((y - pred)**2)
acc = (1 - error / np.var(y)) * 100

print("Mini-Batch GD")
print("Weight:", w)
print("Error:", error)
print("Accuracy:", acc, "%")

"""# **Momentum Gradient Descent**"""

import numpy as np

X = np.array([1,2,3,4])
y = np.array([2,4,6,8])
w = 0.0
v = 0.0
lr = 0.01
beta = 0.9

for _ in range(1000):
    grad = np.mean((w*X - y) * X)
    v = beta * v + lr * grad
    w -= v

pred = w * X
error = np.mean((y - pred)**2)
acc = (1 - error / np.var(y)) * 100

print("Momentum GD")
print("Weight:", w)
print("Error:", error)
print("Accuracy:", acc, "%")

"""# **Activation Functions**"""

import numpy as np

def threshold(x): return np.where(x>=0,1,0)
def sigmoid(x): return 1/(1+np.exp(-x))

x = np.array([-2,-1,0,1,2])
print("Step Output:", threshold(x))
print("Sigmoid Output:", sigmoid(x))